### ISSUE TITLE
Creates unnecessary output for imported methods in the module

### ISSUE THREAD

**Issue by rtibbles** [HumanBrainProject/jsdoc-sphinx#3]
When running with this template, in contrast to the standard output from JSDoc, I find entries in the resultant RST file for functions that have only been defined by import into the module in question.

Compare:

![image](https://cloud.githubusercontent.com/assets/1680573/15055454/8ce8dd1e-12c1-11e6-95a6-95a6a5614c27.png)

with the RST output:
# 
# Module: `assetLoader`

.. contents:: Local Navigation
   :local:
# Children

.. toctree::
   :maxdepth: 1
# Description

Asset Loader module.
Loads frontend assets (JS and CSS) asynchronously, to avoid page bloat, and improve page load time.
# Function `assetLoader`

Take an Array of frontend asset files and asynchronously load in order.

.. js:function:: assetLoader(assets[, callback][, timeout])

```
:param Array assets: An array that contains the paths for each of the files to be loaded.
:param assetLoadCallback callback: A callback that gets called when fetching is complete.
:param Number timeout: A ms timeout after which to error for CSS files - this compensates for the lack of wide
support for the onerror event on 'link' tags in HTML.
```
# Function `scriptjs`

.. js:function:: scriptjs()
# Function `loadcss`

.. js:function:: loadcss()
# Function `onloadcss`

.. js:function:: onloadcss()
# Function `logging`

.. js:function:: logging()
# Function `_`

.. js:function:: _()
# Function `timeout`

.. js:function:: timeout()

**Comment by rtibbles** [comment]
@oliamb Any ideas on where to try to stop this from happening? I have tried looking at the default JSDoc template, but can't quite map how to make that functionality happen in the RST template.

**Comment by oliamb** [comment]
The project against which I ran the doc is not using ES6 (shame), so I cannot really tell.

I just run it against this file for a test https://github.com/wwayne/react-tooltip/blob/master/src/index.js but I don't experiment the same effect. Can you point me to some code that produce this result ; and maybe some details about the command you run against it?

**Comment by oliamb** [comment]
@rtibbles, I managed to reproduce your issue. Can you comment the pull request above?
