### ISSUE TITLE
not pulling in all files

### ISSUE THREAD

**Issue by enuggetry** [HumanBrainProject/jsdoc-sphinx#7]
First time using it.  Not too familiar with rst nor jsdoc.
However, jsdoc with built-in template generates docs for most my classes, but using the jsdoc-sphinx template, it only generated this much and seemed to ignore many of the other js files.  The resulting rst seems to suck in code as well.

`./node_modules/jsdoc/jsdoc.js -t node_modules/jsdoc-sphinx/template -d ./docs ./api/**/*.js
`
`http://jbserver.readthedocs.io
`

[my repo](https://github.com/enuggetry/jbserver/tree/master/docs)

Any hints would be greatly appreciated.

**Comment by enuggetry** [comment]
using it. learning to work around issues.

**Comment by oliamb** [comment]
Sorry to not have answered @enuggetry, I am no working on this lib anymore. I think the HumanBrainProject still use it so you will probably get maintenance upgrade at least :-)
